azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    active-directory-groups: group1

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}